// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9XLq_3zB7NWXbnKJwKXUQ3-x-EPw9q5I',
    appId: '1:121584723723:web:18e7e35534ffa794f2240e',
    messagingSenderId: '121584723723',
    projectId: 'silken-reducer-372413',
    authDomain: 'silken-reducer-372413.firebaseapp.com',
    databaseURL: 'https://silken-reducer-372413-default-rtdb.firebaseio.com',
    storageBucket: 'silken-reducer-372413.appspot.com',
    measurementId: 'G-PCKVGX425C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_hxFwMUKge2raogp5sDNeopdxRssvhJ4',
    appId: '1:121584723723:android:edd630edf05d5841f2240e',
    messagingSenderId: '121584723723',
    projectId: 'silken-reducer-372413',
    databaseURL: 'https://silken-reducer-372413-default-rtdb.firebaseio.com',
    storageBucket: 'silken-reducer-372413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx3pMXZ4pee5XMzsfoHLrKK74AtYiZewI',
    appId: '1:121584723723:ios:eebc77d9c85bb9b1f2240e',
    messagingSenderId: '121584723723',
    projectId: 'silken-reducer-372413',
    databaseURL: 'https://silken-reducer-372413-default-rtdb.firebaseio.com',
    storageBucket: 'silken-reducer-372413.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx3pMXZ4pee5XMzsfoHLrKK74AtYiZewI',
    appId: '1:121584723723:ios:7938efc6b9ede2c3f2240e',
    messagingSenderId: '121584723723',
    projectId: 'silken-reducer-372413',
    databaseURL: 'https://silken-reducer-372413-default-rtdb.firebaseio.com',
    storageBucket: 'silken-reducer-372413.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
